(require 'nico-package)

(require 'nico-ace-jump)
(require 'nico-apg)
(require 'nico-backups)
(require 'nico-darwin)
(require 'nico-dired)
(require 'nico-elisp)
(require 'nico-erc)
(require 'nico-eshell)
(require 'nico-ido)
(require 'nico-js)
(require 'nico-latex)
(require 'nico-magit)
(require 'nico-misc)
(require 'nico-mu4e)
;;(require 'nico-notmuch)
(require 'nico-org)
(require 'nico-org-publish)
(require 'nico-pharo-get)
(require 'nico-smalltalk)
(require 'nico-tramp)
(require 'nico-undotree)
(require 'nico-w3m)
(require 'nico-whitespace)
(require 'nico-writer-mode)
(require 'nico-window-system)
;; (require 'nico-mode-line)
(require 'nico-yasnippet)
;; (require 'nico-el-get)
;; (require 'nico-gnus)
;; (require 'nico-osx)
;; (require 'nico-jabber)

(provide 'nico-modules)
