;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		TeX-insert-backslash
		ace-jump-done
		ace-jump-mode
		ace-jump-move
		artist-forward-char
		backward-sentence
		eval-and-replace
		indent-for-tab-command
		org-beginning-of-line
		org-self-insert-command
		paredit-forward-delete
		paredit-forward-kill-word
		paredit-forward-slurp-sexp
		paredit-open-round
		picture-backward-clear-column
		picture-clear-column
		picture-self-insert
		sgml-slash
		wdired-finish-edit
		yas-expand
		))

(setq mc/cmds-to-run-once
      '(
		edebug-step-mode
		end-of-buffer
		js2r-extract-var
		kill-region
		mu4e
		paredit-semicolon
		))
